default: &default
  adapter: postgresql
  encoding: utf8
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["USER"] %>
  password: <%= ENV["ROOT_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE") { '' } %>_development

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE") { '' } %>_test

production:
  <<: *default
  database: api_production
  username: <%= ENV["USER"] %>
  password: <%= ENV["ROOT_PASSWORD"] %>
