services:
  db:
    container_name: api_db
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_DB: ${DATABASE}
      POSTGRES_PASSWORD: ${ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
    ports:
      - "5432:5432"

  api:
    container_name: api
    build:
      context: backend
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - "./backend:/app"
    ports:
      - "3001:3000"
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file:
      - .env

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/frontend"
    stdin_open: true
    tty: true

volumes:
  db-data: